### ISSUE TITLE
Software lock cannot be controlled

### ISSUE THREAD

**Issue by mattstocum** [pricemi115/grumptechgaragedoor#11]
The documentation states, 

> To provide some measure of security, preventing unintended opening/closing of the doors, a software lock will prevent control of the door. The lock is enabled by default and the state of the lock is not preserved between sessions.

but there is no documentation provided on how to disable the lock and enable control of the garage door.

**Comment by pricemi115** [comment]
Hi @mattstocum 
Thank you for letting me know. A quick question: are you using the Apple Home app (on iOS or macOS) to view this accessory? If so, I think that may be the problem. Some time over the past 6 months or more, I found that I no longer have access to the lock switch. Instead, I prefer to use the Home+ app by Matthias Hochgatterer (https://apps.apple.com/us/app/home-4/id995994352). This app has always worked reliably for me. The image below is how the accessory shows up in Home+ where the control to lock/unlock the door is visible and controllable. 
I will update the documentation indicating this issue.

![image](https://user-images.githubusercontent.com/5100303/81454571-a3d5bf80-915a-11ea-9ccf-70a4522efd7b.png)

**Comment by pricemi115** [comment]
In addition to noting the observed limitations when using the Apple Home application(s), I will be adding an optional configuration setting to allow the software lock to default to the _unsecured_ state. Thereby, allowing users who only use the Apple Home app to control the door, with obvious loss of the lock functionality since they will be unable to secure/re-secure the software lock.

**Comment by pricemi115** [comment]
Fixed over several commits (mostly due to cleanup issues). Did not bother with a pull request.
Commits:
> 836bf07b023c53359ac2bfb6ddd60b6923f7db4d
> 0f70359964ce1bb274eaf4a162e030a9e0451c59
> 531ab430f7fee9f333f35f6f8ef7cbf6bbd90881

**Comment by mattstocum** [comment]
Yes, I was using the Apple Home app, which did not show the lock state. The Eve for HomeKit app showed the lock state and let me toggle it. Thanks!

**Comment by pricemi115** [comment]
Good to know that the Eve for Homekit app is another that properly renders the characteristics for garage doors. - Thanx
